# Generated by Django 2.1.7 on 2019-03-13 19:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('user2', 'user2'), ('hrishabh0901', 'hrishabh0901'), ('user1', 'user1'), ('user3', 'user3')], max_length=10), size=None)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
