# Generated by Django 2.1.7 on 2019-03-14 05:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('user2', 'user2'), ('user1', 'user1'), ('user4', 'user4'), ('hrishabh0901', 'hrishabh0901'), ('user3', 'user3'), ('user5', 'user5')], max_length=10), size=None),
        ),
    ]
