# Generated by Django 2.1.7 on 2019-03-14 10:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20190314_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('user1', 'user1'), ('user2', 'user2'), ('user3', 'user3'), ('hrishabh901', 'hrishabh901'), ('user5', 'user5')], max_length=40), default=None, size=None),
        ),
    ]
