# Generated by Django 2.1.7 on 2019-03-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20190314_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
