# Generated by Django 2.1.7 on 2019-03-14 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Inprogress', 'Inprogress'), ('Done', 'Done')], default='Planned', max_length=15)),
                ('assignee', models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL)),
                ('user_assgined', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
